- name: Clean packages
  command:
   cmd: dnf clean -y packages

- name: Install device-mapper-persistent-data
  dnf:
   name: device-mapper-persistent-data
   state: latest

- name: Install lvm2
  dnf:
   name: lvm2
   state: latest