- hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Clean packages
    command:
      cmd: dnf clean -y packages

  - name: Install device-mapper-persistent-data
    dnf:
      name: device-mapper-persistent-data
      state: latest

  - name: Install lvm2
    dnf:
      name: lvm2
      state: latest

  - name: add repo docker
    command:
      cmd: sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install Docker
    dnf:
      name: docker-ce
      state: present

  - name: Install python3
    dnf:
      name: python3

  - name: Pip install
    dnf:
      name: python3-pip

  - name: Make sure docker is running
    service: name=docker state=started
    tags: docker