name: CI devops 2022 CPE
on:
  push:
   branches: main
  pull_request:

jobs:
 test-backend:
  runs-on: ubuntu-18.04
  steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
       java-version: '11'
       distribution: 'adopt'

    - name: Build and test with Maven
      run: mvn clean verify --file tp1_backend_api/simple-api-main/simple-api